parameters:
  - name: ServiceDirectory
    type: string
    default: ''
  - name: MaxParallel
    type: integer
    default: 0
  BeforeTestSteps: []
  AfterTestSteps: []
  BuildTargetingString: 'azure-*'
  AdditionalTestArgs: ''
  TestMarkArgument: ''
  InjectedPackages: ''
  BuildDocs: true
  JobName: Test
  AllocateResourceGroup: true
  DeployArmTemplate: false
  TestTimeoutInMinutes: 120
  TestSamples: false
  Location: ''
  Matrix:
    Linux_Python35:
      OSVmImage: 'ubuntu-18.04'
      PythonVersion: '3.5'
      CoverageArg: '--disablecov'
    MacOs_Python37:
      OSVmImage: 'macOS-10.15'
      PythonVersion: '3.7'
      CoverageArg: '--disablecov'
    Windows_Python27:
      OSVmImage: 'windows-2019'
      PythonVersion: '2.7'
      CoverageArg: '--disablecov'
    Linux_PyPy3:
      OSVmImage: 'ubuntu-18.04'
      PythonVersion: 'pypy3'
      CoverageArg: '--disablecov'
    Linux_Python39:
      OSVmImage: 'ubuntu-18.04'
      PythonVersion: '3.9'
      CoverageArg: ''
  CloudConfigurations:
    AzureCloud:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
  - name: EnvVars
    type: object
    default: {}

stages:
  - stage: Build
    jobs:
    - template: ../jobs/archetype-sdk-tests.yml
      parameters:
        ServiceDirectory: ${{ parameters.ServiceDirectory }}
        EnvVars: ${{ parameters.EnvVars }}
        MaxParallel: ${{ parameters.MaxParallel }}
        BeforeTestSteps: ${{ parameters.BeforeTestSteps }}
        AfterTestSteps: ${{ parameters.AfterTestSteps }}
        AdditionalTestArgs: ${{ parameters.AdditionalTestArgs }}
        BuildTargetingString: ${{ parameters.BuildTargetingString }}
        TestMarkArgument: ${{ parameters.TestMarkArgument }}
        InjectedPackages: ${{ parameters.InjectedPackages }}
        BuildDocs: ${{ parameters.BuildDocs }}
        JobName: ${{ parameters.JobName }}
        AllocateResourceGroup: ${{ parameters.AllocateResourceGroup }}
        DeployArmTemplate: ${{ parameters.DeployArmTemplate }}
        TestTimeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}
        TestSamples: ${{ parameters.TestSamples }}
        Location: ${{ parameters.Location }}
        Matrix: ${{ parameters.Matrix }}
        CloudConfigurations: ${{ parameters.CloudConfigurations }}


  - stage: Publish_Coverage
    dependsOn: Build
    jobs:
    - template: ../jobs/publish-coverage.yml
      parameters:
        # condition: succeededOrFailed()
        ServiceDirectory: ${{ parameters.ServiceDirectory }}